#%RAML 1.0 Trait

queryParameters:
    number1:
      required: false
      type: integer
      example: 20
          
    number2:
      required: false
      type: integer
      example: 20

responses:
  

        400:
          body:
            application/json:
              example:
                {
                  "message":"not found"
                }
        404:
          body:
            application/json:
              example:
                {
                  "message":"bad request"
                }
          